---

- name: Terraform / Ansible IP Share 
  hosts: cmsbkp 
  gather_facts: False
  become: yes

  tasks:

    - name: Set GitHub Webhook
      become_user: ec2-user
      ansible.builtin.shell: |
        gh webhook forward --repo HarrierPanels/Git \ 
          --events=push --url="http://localhost:8080/github-webhook/"
        echo 'Webhook set!'
      async: 45
      poll: 0

    - name: Git push at localhost 
      become_user: a
      ansible.builtin.shell: |
        cd /home/a/sql
        git add . && git commit -m "Backup & Remove Old by Cron / Ansible"
      register: git
      delegate_to: localhost

    - name: Git push
      ansible.builtin.debug:
        var: git
